name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17.3"
          otp-version: "27.0"

      - name: Install dependencies
        run: mix deps.get

      - name: Format check
        run: mix format --check-formatted

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Test
        run: mix test
