[package]
name = "devkit"
version = "0.4.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
publish = false

[[bin]]
name = "dev"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
devkit-cli = { path = "crates/dev" }

[workspace]
resolver = "2"
members = [
    "crates/dev",
]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
